# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_info.proto',
  package='model_info',
  syntax='proto2',
  serialized_pb=_b('\n\x10model_info.proto\x12\nmodel_info\"u\n\tFormatMap\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05index\x18\x02 \x02(\x05\x12\x11\n\tdebug_doc\x18\x03 \x01(\t\x12\r\n\x05group\x18\x04 \x01(\t\x12\x13\n\x0bid_in_group\x18\x05 \x01(\t\x12\x16\n\x0eindex_in_group\x18\x06 \x01(\x05\"B\n\x0b\x46ormatTable\x12\x0c\n\x04size\x18\x01 \x02(\x05\x12%\n\x06values\x18\x02 \x03(\x0b\x32\x15.model_info.FormatMap\"J\n\tModelInfo\x12)\n\nmodel_type\x18\x01 \x02(\x0e\x32\x15.model_info.ModelType\x12\x12\n\nmodel_path\x18\x02 \x02(\t\"\xdd\x01\n\x1fInsurancePricePredictionRequest\x12\x12\n\nrequest_id\x18\x01 \x02(\t\x12\x0f\n\x07\x63ompany\x18\x02 \x01(\t\x12\x0e\n\x06policy\x18\x03 \x01(\t\x12\x10\n\x08\x63overage\x18\x04 \x01(\x05\x12\x10\n\x08industry\x18\x05 \x01(\x05\x12\x12\n\noccupation\x18\x06 \x01(\x05\x12\x0c\n\x04\x63ity\x18\x07 \x01(\t\x12\x0b\n\x03num\x18\x08 \x01(\x05\x12\x0e\n\x06\x61mount\x18\t \x01(\x02\x12\x0f\n\x07\x61vg_age\x18\n \x01(\x02\x12\x11\n\tsex_ratio\x18\x0b \x01(\x02\"f\n\x1aInsurancePriceResponseData\x12\x12\n\nrisk_ratio\x18\x01 \x01(\x02\x12\x0f\n\x07\x61vg_pay\x18\x02 \x01(\x02\x12\x11\n\tavg_claim\x18\x03 \x01(\x02\x12\x10\n\x08\x61vg_days\x18\x04 \x01(\x02\"\x8c\x01\n InsurancePricePredictionResponse\x12\x13\n\x0bresponse_id\x18\x01 \x02(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x34\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32&.model_info.InsurancePriceResponseData*1\n\tModelType\x12\x0f\n\x0bmodel_error\x10\x00\x12\x13\n\x0finsurance_price\x10\x01')
)

_MODELTYPE = _descriptor.EnumDescriptor(
  name='ModelType',
  full_name='model_info.ModelType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='model_error', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='insurance_price', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=766,
  serialized_end=815,
)
_sym_db.RegisterEnumDescriptor(_MODELTYPE)

ModelType = enum_type_wrapper.EnumTypeWrapper(_MODELTYPE)
model_error = 0
insurance_price = 1



_FORMATMAP = _descriptor.Descriptor(
  name='FormatMap',
  full_name='model_info.FormatMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='model_info.FormatMap.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='model_info.FormatMap.index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='debug_doc', full_name='model_info.FormatMap.debug_doc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group', full_name='model_info.FormatMap.group', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_in_group', full_name='model_info.FormatMap.id_in_group', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_in_group', full_name='model_info.FormatMap.index_in_group', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=149,
)


_FORMATTABLE = _descriptor.Descriptor(
  name='FormatTable',
  full_name='model_info.FormatTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='model_info.FormatTable.size', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='model_info.FormatTable.values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=217,
)


_MODELINFO = _descriptor.Descriptor(
  name='ModelInfo',
  full_name='model_info.ModelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_type', full_name='model_info.ModelInfo.model_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_path', full_name='model_info.ModelInfo.model_path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=293,
)


_INSURANCEPRICEPREDICTIONREQUEST = _descriptor.Descriptor(
  name='InsurancePricePredictionRequest',
  full_name='model_info.InsurancePricePredictionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='model_info.InsurancePricePredictionRequest.request_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='company', full_name='model_info.InsurancePricePredictionRequest.company', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='policy', full_name='model_info.InsurancePricePredictionRequest.policy', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coverage', full_name='model_info.InsurancePricePredictionRequest.coverage', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='industry', full_name='model_info.InsurancePricePredictionRequest.industry', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='occupation', full_name='model_info.InsurancePricePredictionRequest.occupation', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='model_info.InsurancePricePredictionRequest.city', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='model_info.InsurancePricePredictionRequest.num', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='model_info.InsurancePricePredictionRequest.amount', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='avg_age', full_name='model_info.InsurancePricePredictionRequest.avg_age', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sex_ratio', full_name='model_info.InsurancePricePredictionRequest.sex_ratio', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=517,
)


_INSURANCEPRICERESPONSEDATA = _descriptor.Descriptor(
  name='InsurancePriceResponseData',
  full_name='model_info.InsurancePriceResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='risk_ratio', full_name='model_info.InsurancePriceResponseData.risk_ratio', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='avg_pay', full_name='model_info.InsurancePriceResponseData.avg_pay', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='avg_claim', full_name='model_info.InsurancePriceResponseData.avg_claim', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='avg_days', full_name='model_info.InsurancePriceResponseData.avg_days', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=621,
)


_INSURANCEPRICEPREDICTIONRESPONSE = _descriptor.Descriptor(
  name='InsurancePricePredictionResponse',
  full_name='model_info.InsurancePricePredictionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_id', full_name='model_info.InsurancePricePredictionResponse.response_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='model_info.InsurancePricePredictionResponse.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='model_info.InsurancePricePredictionResponse.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='model_info.InsurancePricePredictionResponse.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=624,
  serialized_end=764,
)

_FORMATTABLE.fields_by_name['values'].message_type = _FORMATMAP
_MODELINFO.fields_by_name['model_type'].enum_type = _MODELTYPE
_INSURANCEPRICEPREDICTIONRESPONSE.fields_by_name['data'].message_type = _INSURANCEPRICERESPONSEDATA
DESCRIPTOR.message_types_by_name['FormatMap'] = _FORMATMAP
DESCRIPTOR.message_types_by_name['FormatTable'] = _FORMATTABLE
DESCRIPTOR.message_types_by_name['ModelInfo'] = _MODELINFO
DESCRIPTOR.message_types_by_name['InsurancePricePredictionRequest'] = _INSURANCEPRICEPREDICTIONREQUEST
DESCRIPTOR.message_types_by_name['InsurancePriceResponseData'] = _INSURANCEPRICERESPONSEDATA
DESCRIPTOR.message_types_by_name['InsurancePricePredictionResponse'] = _INSURANCEPRICEPREDICTIONRESPONSE
DESCRIPTOR.enum_types_by_name['ModelType'] = _MODELTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FormatMap = _reflection.GeneratedProtocolMessageType('FormatMap', (_message.Message,), dict(
  DESCRIPTOR = _FORMATMAP,
  __module__ = 'model_info_pb2'
  # @@protoc_insertion_point(class_scope:model_info.FormatMap)
  ))
_sym_db.RegisterMessage(FormatMap)

FormatTable = _reflection.GeneratedProtocolMessageType('FormatTable', (_message.Message,), dict(
  DESCRIPTOR = _FORMATTABLE,
  __module__ = 'model_info_pb2'
  # @@protoc_insertion_point(class_scope:model_info.FormatTable)
  ))
_sym_db.RegisterMessage(FormatTable)

ModelInfo = _reflection.GeneratedProtocolMessageType('ModelInfo', (_message.Message,), dict(
  DESCRIPTOR = _MODELINFO,
  __module__ = 'model_info_pb2'
  # @@protoc_insertion_point(class_scope:model_info.ModelInfo)
  ))
_sym_db.RegisterMessage(ModelInfo)

InsurancePricePredictionRequest = _reflection.GeneratedProtocolMessageType('InsurancePricePredictionRequest', (_message.Message,), dict(
  DESCRIPTOR = _INSURANCEPRICEPREDICTIONREQUEST,
  __module__ = 'model_info_pb2'
  # @@protoc_insertion_point(class_scope:model_info.InsurancePricePredictionRequest)
  ))
_sym_db.RegisterMessage(InsurancePricePredictionRequest)

InsurancePriceResponseData = _reflection.GeneratedProtocolMessageType('InsurancePriceResponseData', (_message.Message,), dict(
  DESCRIPTOR = _INSURANCEPRICERESPONSEDATA,
  __module__ = 'model_info_pb2'
  # @@protoc_insertion_point(class_scope:model_info.InsurancePriceResponseData)
  ))
_sym_db.RegisterMessage(InsurancePriceResponseData)

InsurancePricePredictionResponse = _reflection.GeneratedProtocolMessageType('InsurancePricePredictionResponse', (_message.Message,), dict(
  DESCRIPTOR = _INSURANCEPRICEPREDICTIONRESPONSE,
  __module__ = 'model_info_pb2'
  # @@protoc_insertion_point(class_scope:model_info.InsurancePricePredictionResponse)
  ))
_sym_db.RegisterMessage(InsurancePricePredictionResponse)


# @@protoc_insertion_point(module_scope)
